### ISSUE TITLE
Does it has anything to do with Google's blaze?

### ISSUE THREAD

**Issue by javatlacati** [fizzed/blaze#12]
You know.. the proprietary version of [bazel](https://bazel.build/).

**Comment by jjlauer** [comment]
Not at all.

**Comment by javatlacati** [comment]
So you are no susceptible to having legal issues because of using the name?

**Comment by jjlauer** [comment]
Legal issues for an open source project using a common phrase for something internal tool (that isn't sold) at another company?  Yeah, no.
