### ISSUE TITLE
Is it possible to provide arguments (args) to a script?

### ISSUE THREAD

**Issue by TobseF** [fizzed/blaze#13]
Can I provide arguments which blaze passes to the script? So it would be possible to write:
``` kotlin
fun main(args: Array<String>) {
    print(args)
}
```
and call `java -jar blaze.jar -args mySuperArgument` ?

I saw the [blaze.conf](https://github.com/fizzed/blaze/blob/master/docs/CONFIG.md) property option. But in this way I have to add a blaze dependency / import to my script, which I want to avoid. And it's not flexible enough like arguments.

Or is the java `-Dname=value` the only possibility to pass an argument to a script? Which is not typical if i run the script without blaze, or want to test it with JUnit.

**Comment by jjlauer** [comment]
The -Dname=value method is the intended way of passing command-line
arguments.  You access them in your script as though they were config
parameters.  You don't need a .conf file, but if you did have one, you
actually could supply defaults in the .conf and then simply override them
on the command-line.

The main reason I never added true command-line arguments is that you can
technically ask blaze to run multiple tasks at a time -- e.g. "blaze a b c"
where a, b, and c are all separate tasks.  You'd then require some
convoluted strategy of "blaze a [args for a] b [args for b] c [args for c]"
kind of syntax.  Thus, I actually thought the config -Dname=value strategy
for passing values is somewhat superior in a way.

**Comment by TobseF** [comment]
Thanks for the fast reply. Your idea with the config strategy sounds reasonable, and of course works pretty well in my case. To make it easier to migrate existing scripts something like a `-a|--args` options could help.

**Comment by jjlauer** [comment]
It'd be fairly straight forward to convert "-a arg" to simply by an alias
to "-Da=arg" in the java boostrap code.  I'd be supportive of a PR that
implemented that kind of feature.

**Comment by jjlauer** [comment]
Cleaning up old issues.  This was addressed in recent blaze versions where "--argument" is now supported.
