### ISSUE TITLE
Is it possible to use Blaze with a JRE?

### ISSUE THREAD

**Issue by kimptoc** [fizzed/blaze#6]
Hi,

Wondering if we just include the tools.jar is that sufficient, or maybe the eclipse compiler?

Thanks, Chris.

**Comment by jjlauer** [comment]
@kimptoc good question.  I took a few minutes to add the answer to the docs.  A "server-jre" is good enough or you can just add the eclipse compiler as a runtime dependency and blaze will download it before compiling your script and will use that instead.

https://github.com/fizzed/blaze/blob/master/docs/BASIC.md#running-on-a-jre

**Comment by kimptoc** [comment]
Awesome!

Looks like ServerJRE is pretty much a JDK - http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html 

Which is not whats installed on our servers :(
